name: Sync to personal repo

on:
  push:
    branches:
      - feat/localization

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          ref: feat/localization

      - name: Push to personal repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git remote add personal https://x-access-token:${{ secrets.PERSONAL_REPO_TOKEN_FOR_LOCALIZATION }}@github.com/rabyeoljji/picktoss-localization.git

          git push personal HEAD:main --force
